### ISSUE TITLE
Additional Tri-strip Models / Fixes?

### ISSUE THREAD

**Issue by dreamsyntax** [ShadowSpeedrun/ShadowSX#20]
Required:
```
/character/shadow.one
```

Optional, if SX wants them:
- Bigfoot Type B Glass Glare Bug
- Artificial Chaos Wrong Eye Glow rotation

**Comment by BlazinZzetti** [comment]
Are the any before and after pictures for the potential model updates?

I would prefer to stick with the original models, but depending on the change may consider adding them.

**Comment by dreamsyntax** [comment]
Bigfoot Type B Glass Glare Bug:
Before (there is a floating glass piece, which renders to cam relative, not to the model):
![image](https://github.com/ShadowSpeedrun/ShadowSX/assets/14857235/7bcd6c58-5f76-44df-b6c3-8ea2c0e02f2f)

After (properly rigged to the model, no more weirdness):
![image](https://github.com/ShadowSpeedrun/ShadowSX/assets/14857235/c397c932-573b-4590-8e71-bd08f705286b)


Artificial Chaos - the eyeglow.dff is rotated, nothing else modified
Before:
![image](https://github.com/ShadowSpeedrun/ShadowSX/assets/14857235/3cd19bb4-7e54-479d-9b29-4ce8ce6b991f)

After:
![image](https://github.com/ShadowSpeedrun/ShadowSX/assets/14857235/62a647ce-893e-43a9-aadf-836e6345c9a6)

**Comment by BlazinZzetti** [comment]
Event Models need to be re-exported.  Somehow part of Shadow's back legs got unsmoothed.  This seems to be in every Event, though it's not always in view.
SX 1.0:
![image](https://github.com/ShadowSpeedrun/ShadowSX/assets/24198652/086568bc-12dd-4804-babd-7596e0d4a83d)
SX 1.1:
![image](https://github.com/ShadowSpeedrun/ShadowSX/assets/24198652/e515981f-cb71-4ae9-b7dc-8e9576ececc5)

**Comment by BlazinZzetti** [comment]
Cutscene 5301 used a different model and also needs to have the reduced model size treatment.
![image](https://github.com/ShadowSpeedrun/ShadowSX/assets/24198652/4e24bd0c-32b7-4413-8d8c-cc79c82308e6)

**Comment by dreamsyntax** [comment]
> Cutscene 5301 used a different model and also needs to have the reduced model size treatment

After re-reviewing our hash list, its because its Shadow'L' (low poly) Locator:
![image](https://github.com/ShadowSpeedrun/ShadowSX/assets/14857235/83b550b0-2665-4096-935f-ebe76f0739d6)


Note, simplified hash to last 4 chars, but full hashes (SHA1) are:
```
SHADOW!LOCATOR.DFF
1C07033465A2020BBC2BEE851A782A7A6F14F83A
FA23D5CD6978DAB613FE16E3D4E349A2574A264F
8CD68E5466F7A8725343B49777EF94416F1CDAAD
--
SHADOWL!LOCATOR.DFF
1186D1F0D73BCBA2289B7751C9DABE0A05EC3338

```

New hash list:
```
F83A : event0980_sceneA

DAAD : event0800_sceneA
DAAD : event0801_sceneA
DAAD : event0802_sceneA
DAAD : event0803_sceneA
DAAD : event0804_sceneA
DAAD : event0805_sceneA
DAAD : event0806_sceneA
DAAD : event0807_sceneA
DAAD : event0808_sceneA
DAAD : event0809_sceneA
DAAD : event0810_sceneA
DAAD : event0811_sceneA
DAAD : event0812_sceneA
DAAD : event0813_sceneA
DAAD : event0814_sceneA
DAAD : event0815_sceneA
DAAD : event0816_sceneA
DAAD : event0817_sceneA
DAAD : event0818_sceneA
DAAD : event0819_sceneA
DAAD : event0820_sceneA
DAAD : event0822_sceneA
DAAD : event0823_sceneA
DAAD : event0824_sceneA
DAAD : event0825_sceneA
DAAD : event0826_sceneA
DAAD : event3201_sceneA
DAAD : event4202_sceneA
DAAD : event4311_sceneA
DAAD : event4411_sceneA
DAAD : event5001_sceneA
DAAD : event5101_sceneD
DAAD : event6203_sceneA
DAAD : event6301_sceneA
DAAD : event6302_sceneA
DAAD : event6303_sceneA
DAAD : event6401_sceneA
DAAD : event6402_sceneA
DAAD : event7001_sceneA
DAAD : event7011_sceneA
DAAD : event7101_sceneA
DAAD : event7111_sceneA
DAAD : event7201_sceneA
DAAD : event7211_sceneA
DAAD : event7301_sceneA
DAAD : event7311_sceneA
DAAD : event7401_sceneA
DAAD : event7411_sceneA
DAAD : event7501_sceneA
DAAD : event7511_sceneA
DAAD : event7601_sceneA
DAAD : event7611_sceneA
DAAD : event7701_sceneA
DAAD : event7711_sceneA
DAAD : event7801_sceneA
DAAD : event7811_sceneA
DAAD : event7901_sceneA
DAAD : event7911_sceneA
DAAD : event8002_sceneA
DAAD : event8002_sceneB
DAAD : event8002_sceneD
DAAD : event8002_sceneF
DAAD : event8002_sceneG
DAAD : event8002_sceneH
DAAD : event8005_sceneA
DAAD : event8006_sceneA
DAAD : event8006_sceneC
DAAD : event8006_sceneD
DAAD : event8006_sceneF
DAAD : event8006_sceneG
DAAD : event8006_sceneH
DAAD : event8101_sceneA
DAAD : event8103_sceneA
DAAD : event8106_sceneA
DAAD : event8106_sceneB
DAAD : event8204_sceneA


264F : event0821_sceneA
264F : event0900_sceneA
264F : event0901_sceneA
264F : event0902_sceneA
264F : event0903_sceneA
264F : event0904_sceneA
264F : event0905_sceneA
264F : event0906_sceneA
264F : event0907_sceneA
264F : event0908_sceneA
264F : event0909_sceneA
264F : event0910_sceneA
264F : event0911_sceneA
264F : event0912_sceneA
264F : event0913_sceneA
264F : event0914_sceneA
264F : event0915_sceneA
264F : event0916_sceneA
264F : event0917_sceneA
264F : event0918_sceneA
264F : event0919_sceneA
264F : event0920_sceneA
264F : event0921_sceneA
264F : event0922_sceneA
264F : event0923_sceneA
264F : event0924_sceneA
264F : event0925_sceneA
264F : event0950_sceneA
264F : event0951_sceneA
264F : event0960_sceneA
264F : event0961_sceneA
264F : event2001_sceneA
264F : event2101_sceneA
264F : event2102_sceneA
264F : event2201_sceneA
264F : event2211_sceneA
264F : event3001_sceneA
264F : event3011_sceneA
264F : event3101_sceneA
264F : event4002_sceneA
264F : event4111_sceneA
264F : event4301_sceneA
264F : event5011_sceneA
264F : event5101_sceneE
264F : event5201_sceneA
264F : event5211_sceneA
264F : event5302_sceneA
264F : event5402_sceneA
264F : event5403_sceneA
264F : event6001_sceneF
264F : event6101_sceneA
264F : event6103_sceneA
264F : event6104_sceneA
264F : event6201_sceneA
264F : event6202_sceneA
264F : event8004_sceneA
264F : event8004_sceneB


3338 : event5301_sceneA
```

**Comment by dreamsyntax** [comment]
Regarding wrong normals, Blender export process was wrong, thankfully had nothing to do with Tri-strip. Will be opening a PR that will address this and account for the intentional same-ring shading per different event model.

**Comment by dreamsyntax** [comment]
SX 1.0 Hash Equivalents:

|Original game| = |SX 1.0|
---------------------------------------------------------------------------------
F83A = 105A5A20055B0E87E7871401C5FA42E40D453030 (NO PORT)
DAAD = 105A5A20055B0E87E7871401C5FA42E40D453030
264F =  105A5A20055B0E87E7871401C5FA42E40D453030 (NO PORT)
3338 = 313A36D5EA2CC10CD555965CE5BFF2E8E52FF198

**Comment by dreamsyntax** [comment]
Discussed the findings offline.
New plan:

F83A/DAAD/264F will have one model (SX1.1 Tri-strip [re-export 2, with custom normals fix]) WITH fixed ring lighting.
3338 = will have a SX1.1 Tri-strip re-export of the low poly variant, WITH fixed ring lighting.

We had unintentionally fixed the ring lighting in expert for SX 1.0, so rather than matching the US release with the broken lighting, we will make all consistent.

**Comment by dreamsyntax** [comment]
character/shadow.one change:
https://github.com/ShadowSpeedrun/ShadowSX/pull/25

**Comment by dreamsyntax** [comment]
For 
``` 
    Bigfoot Type B Glass Glare Bug
    Artificial Chaos Wrong Eye Glow rotation
```

RWIO had better outputs than tri-strip option, so not applying tri-strip to these.
Up to you if you want the fixes for SX.
