### ISSUE TITLE
I Can't Work Out How To Get It To Work For Reloaded 1.2

### ISSUE THREAD

**Issue by Grip555** [ShadowSpeedrun/ShadowSX#36]
I've seen a livestream of it working on 1.2, so how do I get this to work on it?

**Comment by BlazinZzetti** [comment]
Reloaded 1.2 uses code from this project, there's no need to try any combine the two.  If you are looking for the custom colors for Shadow, you can use the launcher program to create the textures then move them to your Reloaded files.
